### PR TITLE
feat: added category filter to video listing page

### PR DESCRIPTION
**Pull request by rahulbakshi4**
- Added API call for getting videos from database
- Added category based filter to the videos

### CODE REVIEW

**Review by shilpe26 — APPROVED** [review]
▪️Good that you host your images to the Cloudinary
▪️File Structure is easy to understand
▪️Good variable naming convention used
Good to merge

**Comment by anandsr21harshit** [comment]
Good naming convention
Cloudinary is a new concept for me. Will use this in my project too.

You can merge this

**Review by anandsr21harshit — APPROVED** [review]

**Comment by rahulbakshi4** [comment]
> Good naming convention
> Cloudinary is a new concept for me. Will use this in my project too.
> 
> You can merge this

Thanks for the review.
You should surely check out cloudinary for  
Image hosting

**Review by hrishi82 — APPROVED** [review]
Code looks good to me
Can be merged!

**Pull request merged**
